### ISSUE TITLE
Kubernetes-Vault uses a different format for the -auth file.

### ISSUE THREAD

**Issue by darron** [UKHomeOffice/vault-sidekick#36]
So I've been reduced to installing jq and doing this in a shell script before vault-sidekick runs:

```
export VAULT_TOKEN=$(cat /var/run/secrets/boostport.com/vault-token | jq .clientToken | cut -d'"' -f 2)
```

I think I've traced the issue - here's an example file - [code is here](https://play.golang.org/p/JM85YmJz4n):

```
dfroese@: cat vault-token
{"clientToken":"removed-the-token-that-was-here","accessor":"1removed-the-accessor-that-was-here","leaseDuration":21600,"renewable":true,"vaultAddr":"https://vault.is.here.com"}
[]:~/Desktop/skt
dfroese@: go run main.go
Error: json: cannot unmarshal number into Go value of type string
Data: map[string]string{"accessor":"removed-the-accessor-that-was-here", "clientToken":"removed-the-token-that-was-here"}
Client Token: removed-the-token-that-was-here
```

Would you be open to a PR that was able to handle this sort of file? I think I've traced through the code and have an idea how I'd implement it.

It would be really nice if vault-sidekick could use that file as well - then I wouldn't have to create custom Docker images for each sidekick and could just pass vault-sidekick flags in the k8s manifest.

Thanks for this project - it fills a definite need!

**Comment by darron** [comment]
Here's a link to kubernetes-vault:

https://github.com/Boostport/kubernetes-vault

**Comment by darron** [comment]
I have a small amount of code that does what I want and works well:

https://github.com/darron/vault-sidekick/commit/15817c517362341e4ec61e25ad2efe6bead9a15e

It changes:

1. Adds a flag to options: `vaultAuthFileFormat` that's set to `default` normally.
2. Adds an ENV variable to `vaultAuthFile` - `getEnv("AUTH_FILE", "")` - so it can be specified in the container ENV.
3. Adds a second argument to `readConfigFile` to handle the `vaultAuthFileFormat`.

It seems to work for us just fine - any comments? Is this something you'd merge?

**Comment by gambol99** [comment]
hi @darron ... apologizes, didn't see the github notification of the issue. Yep, this looks reasonable and shouldn't be difficult to add ... I'll take a look at adding

**Comment by darron** [comment]
Thanks @gambol99 - appreciate it!

Let me know if there's anything else you'd like me to do! I can submit a PR, refactor, etc.

**Comment by darron** [comment]
Thanks for merging - closing this.
